### ISSUE TITLE
Error: No default engine was specified and no extension was provided.

### ISSUE THREAD

**Issue by jveres** [kuzzleio/kuzzle-bo#53]
I see this response in the console/browser after installed and started as per the docs:
```
███████████████████████████████████████████████████████
    ██     KUZZLE BO IS READY (port 3000)                ██
    ███████████████████████████████████████████████████████
Error: No default engine was specified and no extension was provided.
    at new View (/root/kuzzle-bo/node_modules/express/lib/view.js:62:11)
    at EventEmitter.render (/root/kuzzle-bo/node_modules/express/lib/application.js:569:12)
    at ServerResponse.render (/root/kuzzle-bo/node_modules/express/lib/response.js:961:7)
    at /root/kuzzle-bo/core/controllers/index.js:7:7
    at Layer.handle [as handle_request] (/root/kuzzle-bo/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/kuzzle-bo/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/root/kuzzle-bo/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/kuzzle-bo/node_modules/express/lib/router/layer.js:95:5)
    at /root/kuzzle-bo/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/root/kuzzle-bo/node_modules/express/lib/router/index.js:330:12)
    at next (/root/kuzzle-bo/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/root/kuzzle-bo/node_modules/express/lib/router/index.js:176:3)
    at router (/root/kuzzle-bo/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/root/kuzzle-bo/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/kuzzle-bo/node_modules/express/lib/router/index.js:312:13)
    at /root/kuzzle-bo/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/root/kuzzle-bo/node_modules/express/lib/router/index.js:330:12)
    at next (/root/kuzzle-bo/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle [as handle_request] (/root/kuzzle-bo/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/root/kuzzle-bo/node_modules/express/lib/router/index.js:312:13)
    at /root/kuzzle-bo/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/root/kuzzle-bo/node_modules/express/lib/router/index.js:330:12)
    at next (/root/kuzzle-bo/node_modules/express/lib/router/index.js:271:10)
    at SendStream.error (/root/kuzzle-bo/node_modules/serve-static/index.js:120:7)
    at emitOne (events.js:96:13)
    at SendStream.emit (events.js:188:7)
    at SendStream.error (/root/kuzzle-bo/node_modules/send/index.js:245:17)
    at SendStream.onStatError (/root/kuzzle-bo/node_modules/send/index.js:356:12)
```

**Comment by AnthonySendra** [comment]
Hello,

Could you tell us what is your Kuzzle BO image version?
You could retrieve it with `docker images`. Or maybe you could give us the `docker-compose` file or the command you ran.

**Comment by jveres** [comment]
Hi,
I git cloned the sources from the main branch which is versioned as 1.0.0-RC2.
I also tried the 1.0.0-RC2 release zip, same result.

**Comment by xbill82** [comment]
ok, there must be some difference between the execution in Docker and the manual one, since I haven't been able to reproduce it in the first case. Let us take a look at that, thank you for reporting!

**Comment by jveres** [comment]
Yep, it needs ```npm run build``` and voila:)

**Comment by xbill82** [comment]
Oh, you're definitely right! The documentation isn't up to date since we merged Webpack in. Fixing that as soon as possible!
Thanks!
